### ISSUE TITLE
Merge this repository into dkpro-similarity

### ISSUE THREAD

**Issue by logological** [dkpro/similarity-gpl-tmp#2]
This repository was created as a temporary place to store the GPL modules for DKPro Similarity during the migration to the [dkpro-similarity](https://github.com/dkpro/dkpro-similarity) repository.

It looks like the directories from this repository now appear in dkpro-similarity.  Has the migration been completed, then?  Can this repository be deleted?

**Comment by reckart** [comment]
This was merged over, yes. The repository was kept in case something had been going wrong, but it seems to be all ok. I guess we can delete it now.

**Comment by logological** [comment]
Any objections to deleting this repository, @zesch ?

**Comment by zesch** [comment]
No objections.
